### ISSUE TITLE
Line ending consistency?

### ISSUE THREAD

**Issue by Nnubes256** [CCDirectLink/CCModDB#1]
Should we force mods into using LF line endings to ensure consistency? Note that:
- Most sane code editors are able to handle both line endings automatically.
- Git can be told to automatically convert CRLF into LF and the other way around with a .gitattributes file in the mod's repository root.
- This may not matter if NW.js can handle both line endings when loading resources.

Discuss.

**Comment by omegalink12** [comment]
NW is based on chrome and I think people would have noticed if half the internet pages didn't work :P 
Just tried LF,CR,CRLF endings and they all worked.

**Comment by Nnubes256** [comment]
Sounds like there's no need for consistency on line endings in that case. Closing. If anyone has to argument otherwise, please reopen and comment.
